"""add reviews table

Revision ID: 642c4759fefe
Revises: 74a3bfad4b57
Create Date: 2026-09-13 22:34:39.942615

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "642c4759fefe"
down_revision: str | Sequence[str] | None = "74a3bfad4b57"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("rating", sa.Float(), server_default=sa.text("0"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "rating")
    # ### end Alembic commands ###
