services:

  db:
    image: postgres:18-alpine
    container_name: pg-ecommerce
    environment:
      POSTGRES_PASSWORD: admin12345
      POSTGRES_USER: ecommerce_user
      POSTGRES_DB: ecommerce_db
    ports:
      - "9911:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ecommerce_user", "-d", "ecommerce_db"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped


volumes:
  pgdata:
  