[project]
name = "fastapi-ecommerce"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "greenlet>=3.5.5",
    "mypy>=2.3.1",
    "pwdlib[argon2]>=0.3.1",
    "pydantic[email]>=2.13.5",
    "pyjwt>=2.13.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.4",
]

[dependency-groups]
dev = [
    "ruff>=0.16.5",
]

[tool.mypy]
strict = true

[tool.ruff]
target-version = "py312"
line-length = 98
fix = true
extend-exclude = [
    ".venv",
    ".git",
    "__pycache__",
    "build",
    "dist"
]

[tool.ruff.lint]
select = [
    "E", "F", "I", "UP", "B", "C4"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
